# NumPy

In [1]:
import numpy as np

In [10]:
x = np.arange(0,10)
print(x[2:4])

[2 3]


In [17]:
y = np.full(10, 2)
y

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
sq = np.full([2,2], 1)
sq

array([[1, 1],
       [1, 1]])

In [2]:
import random
r = np.arange(5, 15, 1)
random.shuffle(r)
r.reshape(2, 5).T

array([[ 8, 13],
       [11,  6],
       [14,  5],
       [ 7, 12],
       [ 9, 10]])

In [35]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [3]:
e = np.eye(5, 5)
k = np.arange(10, 15, 1)
random.shuffle(k)
mul = e*k
mul

array([[14.,  0.,  0.,  0.,  0.],
       [ 0., 12.,  0.,  0.,  0.],
       [ 0.,  0., 13.,  0.,  0.],
       [ 0.,  0.,  0., 11.,  0.],
       [ 0.,  0.,  0.,  0., 10.]])

In [50]:
a = np.full(3, 1)
b = np.full(3, 1)
np.dot(a, b)

3

## Задание №1.

In [4]:
def get_reverse_vector(start, stop, step):
    return np.arange(start, stop, -1 * step)

In [5]:
x = get_reverse_vector(10, 0, 1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Задание №2.

In [6]:
E = np.eye(10)
Diag = E*x
Tr = 0
for i in range(len(Diag)):
    Tr += Diag[i][i]
Tr

55.0

## Задание №3.

Дана система линейных уравнений

\begin{equation*}
\LARGE
4x + 2y + z = 4 \\
\LARGE
x + 3y = 12 \\
\LARGE
5y + 4z = -3
\end{equation*}

In [18]:
from numpy import linalg

A = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])
B = np.array( [4, 12, -3] )

XYZ = linalg.solve(A, B)
print(f'X: {XYZ[0]}, Y: {XYZ[1]}, Z: {XYZ[2]}')
print('Проверка решения (А*XYZ = B):', np.dot(A, XYZ))

X: 0.4666666666666668, Y: 3.844444444444444, Z: -5.555555555555555
Проверка решения (А*XYZ = B): [ 4. 12. -3.]


## Задание №4.

In [19]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [53]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [45]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [54]:
similar = 0
for i in range(len(users_stats)):
    if cosine(users_stats[i], next_user_stats) > similar:
        similar = cosine(users_stats[i], next_user_stats)
        user_id = i + 1
    else:
        pass
print(f'A user #{user_id} as similar to new one as posible - {similar}')

A user #8 as similar to new one as posible - 0.9486832980505138
